name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macOS-validate:
    runs-on:  macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Audit cask
        run: brew audit --cask ${PWD}/Casks/vulkan-sdk.rb 

