name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macos-test-build-release:
    runs-on:  macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Vulkan SDK
        run: |
          brew audit --cask Casks/vulkan-sdk.rb 
          brew tap Casks/vulkan-sdk.rb 
          brew install --cask vulkan-sdk --force --verbose --debug
